# Hosted zone
domain: example.com

# Slack notification about failover (optional)
slack_hook:
slack_channel: mytestchannel

valkey_config_dir: /opt/valkey
valkey_haproxy_config_dir: /opt/haproxy
valkey_data_dir: /data
valkey_log_dir: /var/log/valkey

valkey_haproxy_crt_file: "{{ valkey_data_dir }}/example.crt"
valkey_haproxy_key_file: "{{ valkey_data_dir }}/example.key"

valkey_default_acl: "~* &* +@all"
valkey_users_acl: ""

# Default ports which will be used with cluster/service specific offset
redis_port: 36379
valkey_port: "{{ redis_port }}"
sentinel_port: 26379
haproxy_api_port: 9899
haproxy_stats_port: 7000
haproxy_valkey_local_port: 46379
haproxy_valkey_local_ssl_port: 56379
haproxy_valkey_ssl_port: 6379
haproxy_sentinel_ssl_port: 16379

# Cluster > subcluster > instance.
# DNS: <subcluster>N.<cluster>.example.com. Example: valkeydb1.testcluster1.example.com
# All subcluster names should start with "valkeydb". Default subcluster name is valkeydb.
instances:
  testcluster1:
    valkeydb-mytest:
      srv1: 10.0.7.72
      srv2: 10.0.7.142
      srv3: 10.0.7.202

  # testcluster2:
  #   valkeydb:
  #     srv1: 10.0.2.1
  #     srv2: 10.0.2.2
  #     srv3: 10.0.2.3
  # testcluster3:
  #   valkeydb:
  #     srv1: 10.0.3.1
  #     srv2: 10.0.3.2
  #     srv3: 10.0.3.3
  #   valkeydb-testsubcluster:
  #     srv1: 10.0.3.4
  #     srv2: 10.0.3.5
  #     srv3: 10.0.3.6


# Cluster > subcluster > service.
# Each service is a combination of 3 containers - redis/sentinel/haproxy running on 3 instances.
# Each service should use an unique port offset within the whole cluster, not just subcluster.
services:
  testcluster1:
    valkeydb-mytest:
      default:
        port_offset: 0
        maxmemory: 400mb
        users:
          user:
            acl: ~user_* +@sortedset +ping +scan +set +get

  #     dev:
  #       port_offset: 1
  #       maxmemory: 150mb
  #     qa:
  #       port_offset: 2
  #       maxmemory: 100mb
  # testcluster2:
  #   valkeydb:
  #     default:
  #       port_offset: 0
  #       maxmemory: 100mb
  #     testdb1:
  #       port_offset: 1
  #       maxmemory: 100mb
  # testcluster3:
  #   valkeydb:
  #     default:
  #       port_offset: 0
  #       maxmemory: 100mb
  #   valkeydb-testsubcluster:
  #     default:
  #       port_offset: 0
  #       maxmemory: 100mb

# Cluster/service specific passwords (can be encrypted by ansible-vault)
secrets:
  testcluster1:
    valkeydb-mytest:
      default:
        password: testpass1        
        users:
          - { login: user, password: pass }

  #     dev:
  #       password: testpass2
  #     qa:
  #       password: testpass3
  # testcluster2:
  #   valkeydb:
  #     default:
  #       password: testpass1
  #     testdb1:
  #       password: testpass2
  # testcluster3:
  #   valkeydb:
  #     default:
  #       password: testpass1
  #   valkeydb-testsubcluster:
  #     default:
  #       password: testpass2
